# Generated by Django 5.2.4 on 2025-07-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_expenseincome_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseincome',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
